version: '3'

networks:
  desenv-network:
    driver: bridge

services:
  rabbitmq:
    build:
      context: ./queue/
      dockerfile: ./Dockerfile
    ports:
      - 15672:15672
      - 5671-5672:5671-5672
    image: rabbitmq:1.0.0
    container_name: rabbitmq
    networks:
      - desenv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 10s
      retries: 5

  loja:
    build:
      context: ./loja/
      dockerfile: ./Dockerfile
    environment:
      - ENV_RABBITMQ_HOST=rabbitmq
      - ENV_RABBITMQ_PORT=5672
      - ENV_RABBITMQ_USER=guest
      - ENV_RABBITMQ_PASS=guest
      - ENV_QUEUE_NAME=raptorslog.queue
      - ENV_QUEUE_EXCHANGE=raptorslog.exchange
      - ENV_QUEUE_ROUTE_KEY=raptorslog.routingkey
    ports:
      - 8080:8090
    image: loja:1.0.0
    container_name: loja
    networks:
      - desenv-network
    links:
      - "rabbitmq:rabbitmq"
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  transportadora:
    build:
      context: ./transportadora/
      dockerfile: ./Dockerfile
    environment:
      - ENV_RABBITMQ_HOST=rabbitmq
      - ENV_RABBITMQ_PORT=5672
      - ENV_RABBITMQ_USER=guest
      - ENV_RABBITMQ_PASS=guest
      - ENV_QUEUE_NAME=raptorslog.queue
    ports:
      - 8081:8080
    image: transportadora:1.0.0
    container_name: transportadora
    networks:
      - desenv-network
    links:
      - "rabbitmq:rabbitmq"
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  transportadora-dispatcher:
    build:
      context: ./transportadora-dispatcher/
      dockerfile: ./Dockerfile
    environment:
      - ENV_RABBITMQ_HOST=rabbitmq
      - ENV_RABBITMQ_PORT=5672
      - ENV_RABBITMQ_USER=guest
      - ENV_RABBITMQ_PASS=guest
      - ENV_QUEUE_NAME=raptorslog.queue
      - ENV_ENTREGADOR=http://entregador:8070
      - ENV_ENTREGADOR_AM=http://entregado-am:8071
    ports:
      - 8083:8081
    image: transportadora-dispatcher:1.0.0
    container_name: transportadora-dispatcher
    networks:
      - desenv-network
    links:
      - "entregador:entregador"
      - "entregador-am:entregador-am"
      - "rabbitmq:rabbitmq"
    depends_on:
      - rabbitmq
      - entregador
      - entregador-am
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  entregador:
    build:
      context: ./entregador/
      dockerfile: ./Dockerfile
    ports:
      - 8082:8070
    image: entregador:1.0.0
    container_name: entregador
    networks:
      - desenv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  entregador-am:
    build:
      context: ./entregador-AM/
      dockerfile: ./Dockerfile
    ports:
      - 8084:8071
    image: entregador-am:1.0.0
    container_name: entregador-am
    networks:
      - desenv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  entregador-mg:
    build:
      context: ./entregador-MG/
      dockerfile: ./Dockerfile
    ports:
      - 8085:8072
    image: entregador-mg:1.0.0
    container_name: entregador-mg
    networks:
      - desenv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8072/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5
