apiVersion: v1
kind: Service
metadata:
  labels:
    app: entregador-mg
  name: entregador-mg-svc
  namespace: raptorslog
spec:
  type: ClusterIP
  ports:
    - name: app-port
      protocol: TCP
      port: 8072
      targetPort: 8072
  selector:
    app: entregador-mg

