apiVersion: v1
kind: Service
metadata:
  labels:
    app: entregador-rs
  name: entregador-rs-svc
  namespace: raptorslog
spec:
  type: ClusterIP
  ports:
    - name: app-port
      protocol: TCP
      port: 8070
      targetPort: 8070
  selector:
    app: entregador-rs

