apiVersion: v1
kind: Service
metadata:
  labels:
    app: loja
  name: loja-svc
  namespace: raptorslog
spec:
  type: LoadBalancer
  ports:
    - name: app-port
      nodePort: 31930
      protocol: TCP
      port: 80
      targetPort: 8090
  selector:
    app: loja