apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: entregador
    version: v1
  name: entregador-v1
  namespace: raptorslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entregador
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: entregador
        version: v1
        environment: dev
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: entregador:1.0.0
          name: entregador
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          ports:
            - containerPort: 8070
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10