apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: transportadora-consumer
    version: v1
  name: transportadora-consumer-v1
  namespace: raptorslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transportadora-consumer
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transportadora-consumer
        version: v1
        environment: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: transportadora-consumer:1.0.0
          name: transportadora-consumer
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: ENV_RABBITMQ_HOST
              value: "rabbitmq"
            - name: ENV_RABBITMQ_PORT
              value: "5672"
            - name: ENV_RABBITMQ_USER
              value: "guest"
            - name: ENV_RABBITMQ_PASS
              value: "guest"
            - name: ENV_QUEUE_NAME
              value: "raptorslog.queue"
            - name: ENV_QUEUE_EXCHANGE
              value: "raptorslog.exchange"
            - name: ENV_QUEUE_ROUTE_KEY
              value: "raptorslog.routingkey"
            - name: ENV_TRANSPORTADORA_DISPATCHER
              value: "http://transportadora-dispatcher:8082"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10