apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    version: v1
  name: rabbitmq-v1
  namespace: raptorslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
        version: v1
        environment: dev
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: rabbitmq:1.0.0
          name: rabbitmq
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          ports:
            - name: http-15672
              containerPort: 15672
            - name: tcp-5671
              containerPort: 5671
            - name: tcp-5672
              containerPort: 5672
            - name: epmd # don't touch this config
              containerPort: 4369 # don't touch this config
          readinessProbe:
            httpGet:
              path: /
              port: http-15672
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10