#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: entregador-am-gateway
#  namespace: raptorslog
#spec:
#  selector:
#    istio: ingressgateway # use istio default controller
#  servers:
#    - port:
#        number: 80
#        name: http
#        protocol: HTTP
#      hosts:
#        - "*"
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: entregador-am-gateway
#  namespace: raptorslog
#spec:
#  hosts:
#    - "*"
#  gateways:
#    - entregador-am-gateway
#  http:
#    - match:
#        - port: 8071
#      route:
#        - destination:
#            host: entregador-am-svc
#            port:
#              number: 8071