apiVersion: v1
kind: Service
metadata:
  labels:
    app: entregador-am
  name: entregador-am-svc
  namespace: raptorslog
spec:
  type: ClusterIP
  ports:
    - name: app-port
      protocol: TCP
      port: 8071
      targetPort: 8071
  selector:
    app: entregador-am

