apiVersion: v1
kind: Service
metadata:
  labels:
    app: transportadora-receiver
  name: transportadora-receiver-svc
  namespace: raptorslog
spec:
  type: ClusterIP
  ports:
    - name: app-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: transportadora-receiver
