apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: transportadora
  namespace: raptorslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transportadora
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transportadora
        environment: dev
    spec:
      containers:
        - image: transportadora:1.0.0
          name: transportadora
          ports:
            - containerPort: 8080
              name: app-port
          env:
            - name: ENV_RABBITMQ_HOST
              value: "rabbitmq-svc"
            - name: ENV_RABBITMQ_PORT
              value: "5672"
            - name: ENV_RABBITMQ_USER
              value: "guest"
            - name: ENV_RABBITMQ_PASS
              value: "guest"
            - name: ENV_QUEUE_NAME
              value: "raptorslog.queue"
            - name: ENV_ENTREGADOR
              value: "http://entregador-svc:8070"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: app-port
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10